language: node_js
node_js:
  - "8"

matrix:
  include:
    - os: linux
      dist: trusty
      install:
        - npm install -g coveralls
      before_script:
        - yarn install
      script:
        - yarn lint
        - yarn ganache &
        - npx zos session --network development
        - npx zos push --deploy-dependencies
        - yarn test
        - npm run coverage && cat coverage/lcov.info | coveralls
